[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13

[window]
padding.x = 14
padding.y = 14
option_as_alt = "both"
decorations = "Buttonless"
opacity = 0.98

